ci(deploy): update deploy workflows
Change-Id: I7df8e91f191b65a8fba093f235f7d5b65ac126e8

diff --git a/.github/workflows/prod-build.yml b/.github/workflows/prod-build.yml
--- a/.github/workflows/prod-build.yml
+++ b/.github/workflows/prod-build.yml
@@ -34,7 +34,7 @@ jobs:
           ssh -o StrictHostKeyChecking=no -N -D 1081 ${{ secrets.TOOLFORGE_USER }}@tools-login.wmflabs.org &
           SSH_JOB="$!"
 
-          # This trap will get overrided below, but also set it here just in case HPTS fails to
+          # This trap will get overriden below, but also set it here just in case HPTS fails to
           # start.
           trap "kill $SSH_JOB" EXIT
 
@@ -51,7 +51,7 @@ jobs:
           # Run own script to login and publish the build results to pages.
           npm run deploy --noi18n
       - name: Create source maps folder
-        run: cd dist && mkdir source-maps && cp *.map.json source-maps
+        run: cd dist && mkdir source-maps && cp *.map source-maps
       - name: Deploy source maps
         uses: easingthemes/ssh-deploy@v2.2.11
         env:
